services:
  php:
    container_name: php_${PROJECT_DIR}
    build:
      context: volume/php
    volumes:
      - ./${PROJECT_DIR}:${PROJECT_ROOT}/${PROJECT_DIR}
      - ./volume/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./volume/php/zz-fpm-user.conf:/usr/local/etc/php-fpm.d/zz-fpm-user.conf
      - ./volume/php/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
      - ./volume/socket:/socket
  nginx:
    container_name: nginx_${PROJECT_DIR}
    build:
      context: volume/nginx
    volumes_from:
      - php
    volumes:
      - ./volume/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./volume/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    ports: ['80:80']
